# Generated by Django 5.2.2 on 2026-01-04 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='文檔的唯一標識符', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='文檔標題', max_length=255)),
                ('content', models.JSONField(default=dict, help_text='文檔內容，以JSON格式存儲')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='文檔創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='文檔最後更新時間')),
                ('owner', models.ForeignKey(help_text='文檔擁有者', on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文檔',
                'verbose_name_plural': '文檔',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', '只讀'), ('write', '編輯')], default='write', help_text='權限級別', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='協作關係創建時間')),
                ('document', models.ForeignKey(help_text='關聯的文檔', on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='docs_app.document')),
                ('user', models.ForeignKey(help_text='協作者用戶', on_delete=django.db.models.deletion.CASCADE, related_name='document_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文檔協作者',
                'verbose_name_plural': '文檔協作者',
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-updated_at'], name='docs_app_do_owner_i_569234_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='docs_app_do_created_cbffa7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaborator',
            index=models.Index(fields=['document', 'user'], name='docs_app_do_documen_a3199c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcollaborator',
            index=models.Index(fields=['user'], name='docs_app_do_user_id_7d23b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcollaborator',
            unique_together={('document', 'user')},
        ),
    ]
