# Generated by Django 5.2.2 on 2026-01-05 12:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='版本的唯一標識符', primary_key=True, serialize=False)),
                ('content', models.JSONField(default=dict, help_text='完整的 Quill Delta 內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='版本創建時間')),
                ('version_number', models.PositiveIntegerField(help_text='版本號')),
                ('created_by', models.ForeignKey(help_text='創建此版本的用戶', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='關聯的文檔', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs_app.document')),
            ],
            options={
                'verbose_name': '文件版本',
                'verbose_name_plural': '文件版本',
                'ordering': ['-version_number'],
                'indexes': [models.Index(fields=['document', '-version_number'], name='docs_app_do_documen_847933_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
