# Generated by Django 5.2.2 on 2025-06-18 00:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': '文檔', 'verbose_name_plural': '文檔'},
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.JSONField(default=dict, help_text='文檔內容，以JSON格式存儲'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='文檔創建時間'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='文檔的唯一標識符', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(help_text='文檔擁有者', on_delete=django.db.models.deletion.CASCADE, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='與此文檔共享的用戶', related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(help_text='文檔標題', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='文檔最後更新時間'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-updated_at'], name='docs_app_do_owner_i_569234_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['-created_at'], name='docs_app_do_created_cbffa7_idx'),
        ),
    ]
