# Generated by Django 5.2.2 on 2026-01-06 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0002_documentversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='評論的唯一標識符', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='評論內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
                ('author', models.ForeignKey(help_text='評論作者', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='關聯的文檔', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='docs_app.document')),
                ('parent', models.ForeignKey(blank=True, help_text='父評論（若為回覆）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='docs_app.comment')),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['document', 'created_at'], name='docs_app_co_documen_ab2120_idx'), models.Index(fields=['parent'], name='docs_app_co_parent__5dd2d5_idx')],
            },
        ),
    ]
