# Generated by Django 6.0.3 on 2026-04-01 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0003_add_comment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentcollaborator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='documentcollaborator',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='unique_document_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='unique_document_version'),
        ),
    ]
